### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by zbirenbaum** [hieudo-hn/SealChipModel#1]
- [x] Rename dnn_mmod_seal.cpp to something that indicates it trains the model
- [x] Update cmake list with new name for dnn_mmod_seal.cpp
- [x] Write script to autocomplete build operations
- [x] organize directory structure and edit cmake

**Comment by zbirenbaum** [comment]
we gucci, closing issue
